version: "3.9"
volumes:
  pgdata:
  static_volume:
networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
services:
  nginx_proxy:
    container_name: nginx_proxy
    build: ./nginx
    restart: unless-stopped
    ports:
      - 1333:80
    depends_on:
      - project_django
    networks:
      - nginx_network
    volumes:
      - static_volume:/app/staticfiles/


  postgres_sql:
    container_name: postgres_sql
    image:  postgres:latest
    env_file:
      - ./.envDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netology_stocks_products"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    command: -p 5555
    expose:
      - "5555"
    ports:
      - "5555:5555"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ./logs:/var/log
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  project_django:
    container_name: project_django
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sh -c "python ./manage.py migrate && python ./manage.py collectstatic && gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000 --workers=4"
    ports:
      - "8000:8000"
    depends_on:
      - postgres_sql
    networks:
      - nginx_network
      - postgres_network
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/staticfiles/
